
## This code implements the TSxFSA product Construction - Disha

from random import uniform
import networkx as nx
from networkx.classes.digraph import DiGraph
from networkx.algorithms import dfs_labeled_edges
import math
import numpy as np
from collections import OrderedDict
import pyvisgraph as vg
from shapely.geometry import Point, LineString
# from uniform_geometry import sample_uniform_geometry
from scipy.stats import truncnorm


class Biased_Product_Tree(object):
    """
    Implements the TSxFSA product tree construction as proposed in STYLUS*
    """
    def __init__(self, ts, fsa, init_state, init_label, para):
        self.ts = ts 
        self.fsa = fsa

        # self.fsa.final - is a set. Storing the final states in a list for now
        self.final_states = list(self.fsa.final)    ## Currently assuming only one final state in the fsa


        # print("finals:", self.final_states[0])
        self.init = init_state

        # initlizing the tree
        self.biased_tree = DiGraph(type='PBA', init=self.init)
        self.biased_tree.add_node(self.init, cost=0, label=init_label)
        
        # directly taken from TLRRT* code - parameters regarding TL-RRT* algorithm
        self.goals = set()
        self.step_size = para['step_size']
        self.lite = para['is_lite'] ### ?
        # size of the ball used in function near
        # uni_v = np.power(np.pi, self.robot*self.dim/2) / math.gamma(self.robot*self.dim/2+1)  ###D: how is the size obtained?
        uni_v = np.pi

        # self.gamma = np.ceil(4 * np.power(1/uni_v, 1./(self.dim*self.robot)))   # unit workspace
        self.gamma = 3.0

        # parameters regarding biased sampling
        # group the nodes in the tree by the buchi state
        self.group = dict()
        self.add_group(self.init)
        
        self.min_dis = np.inf
        self.q_min2final = []
        self.not_q_min2final = []
        self.update_min_dis2final_and_partition(self.init)
        # print("buchi_final", self.buchi.buchi_graph.graph['accept'])

        # we initially assume all transitions to be feasible
        # TODO: Optimize the framework by considering only the feasible transitions



    def update_min_dis2final_and_partition(self, q_p_new):
        """
         check whether q_p_new has the buchi component with minimum distance to the final state
         if so, update the set b_min which collects the buchi states with minimum distance to the final state
         and the set q_min2final which collects nodes in the tree with buchi states in b_min
        :param q_p_new: new product state
        """
        # smaller than the current nodes with minimum distance
        print("qpnew:", q_p_new[1][1])
        print("final:", self.final_states[0][1])
        ## Sidenote : check if the shortest_path method is the fastest implementation
        if len(nx.shortest_path(self.fsa.g, q_p_new[1], self.final_states[0])) < self.min_dis:
            # self.min_dis = self.fsa.min_length[(q_p_new[1], self.fsa_final)]
            self.min_dis = nx.dijkstra_path_length(self.fsa.g, q_p_new[1], self.final_states[0], weight='weight')
            self.path_fsa = nx.bidirectional_shortest_path(self.fsa.g, q_p_new[1], self.final_states[0])

            print("path:", self.path_fsa)
            self.not_q_min2final = self.not_q_min2final + self.q_min2final
            self.q_min2final = [q_p_new]
            self.obtain_symbols()
        # equivalent to
        elif nx.shortest_path(self.fsa.g, q_p_new[1], self.final_states[0]) == self.min_dis:
            self.q_min2final = self.q_min2final + [q_p_new]
        # larger than
        else:
            self.not_q_min2final = self.not_q_min2final + [q_p_new] ### D: Why do we need this?
            
            
    def add_group(self, q_p):
        """
        add q_p to the group within which all states have the same buchi state
        :param q_p: a product state
        """
        try:
            self.group[q_p[1]].append(q_p)
        except KeyError:
            self.group[q_p[1]] = [q_p]


    def project_ts(self, ts):

        """
        Project the symbols on the TS to find the min cost path
        """

        raise NotImplementedError


    def obtain_symbols(self):

        """
        Obtain the symbols to be generated by the TS for the shortest path (min potential path) in product FSA
        """

        node_from = self.path_fsa[0]
        node_to = self.path_fsa[1]

        in_prop, out_prop = self.fsa.g.get_edge_data(node_from, node_to)
        print("in:", in_prop, out_prop, node_from, node_to)
        # raise NotImplementedError

